2021-09-13 19:32:15,277 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:32:15,277 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:32:15,278 INFO    MainThread:9504 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210913_193215-22w7thw7\logs\debug.log
2021-09-13 19:32:15,278 INFO    MainThread:9504 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210913_193215-22w7thw7\logs\debug-internal.log
2021-09-13 19:32:15,279 INFO    MainThread:9504 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D8861D6CA0>
2021-09-13 19:32:15,332 INFO    MainThread:9504 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:32:15,332 INFO    MainThread:9504 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:32:15,333 INFO    MainThread:9504 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3e1mjyoh
2021-09-13 19:32:15,333 INFO    MainThread:9504 [wandb_run.py:finish():1271] finishing run khushal/2final-weather-recognization/3e1mjyoh
2021-09-13 19:32:15,337 INFO    MainThread:9504 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-13 19:32:15,337 INFO    MainThread:9504 [wandb_run.py:_restore():1543] restore
2021-09-13 19:32:16,367 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 483
}

2021-09-13 19:32:16,508 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 483
}

2021-09-13 19:32:17,123 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 483
}

2021-09-13 19:32:17,224 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21068
}

2021-09-13 19:32:17,325 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21068
}

2021-09-13 19:32:17,426 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21068
}

2021-09-13 19:32:17,528 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21068
}

2021-09-13 19:32:17,629 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21068
}

2021-09-13 19:32:17,730 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21068
}

2021-09-13 19:32:17,831 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21068
}

2021-09-13 19:32:17,934 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21068
}

2021-09-13 19:32:18,035 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 14349
  total_bytes: 21068
}

2021-09-13 19:32:18,136 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21068
  total_bytes: 21068
}

2021-09-13 19:32:18,237 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21068
  total_bytes: 21068
}

2021-09-13 19:32:18,339 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21068
  total_bytes: 21068
}

2021-09-13 19:32:18,440 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21068
  total_bytes: 21068
}

2021-09-13 19:32:18,542 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21068
  total_bytes: 21068
}

2021-09-13 19:32:18,644 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21068
  total_bytes: 21068
}

2021-09-13 19:32:18,745 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21068
  total_bytes: 21068
}

2021-09-13 19:32:19,673 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21068
  total_bytes: 21068
}

2021-09-13 19:32:19,775 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21068
  total_bytes: 21068
}

2021-09-13 19:32:21,168 INFO    MainThread:9504 [wandb_run.py:_show_files():1915] logging synced files
2021-09-13 19:32:21,172 INFO    MainThread:9504 [wandb_init.py:init():424] starting backend
2021-09-13 19:32:21,173 INFO    MainThread:9504 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-13 19:32:21,178 INFO    MainThread:9504 [backend.py:ensure_launched():135] starting backend process...
2021-09-13 19:32:21,281 INFO    MainThread:9504 [backend.py:ensure_launched():139] started backend process with pid: 6040
2021-09-13 19:32:21,282 INFO    MainThread:9504 [wandb_init.py:init():429] backend started and connected
2021-09-13 19:32:21,283 INFO    MainThread:9504 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-13 19:32:21,284 INFO    MainThread:9504 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-13 19:32:21,284 INFO    MainThread:9504 [wandb_init.py:init():477] updated telemetry
2021-09-13 19:32:21,285 INFO    MainThread:9504 [wandb_init.py:init():500] communicating current version
2021-09-13 19:32:24,429 INFO    MainThread:9504 [wandb_init.py:init():505] got version response 
2021-09-13 19:32:24,430 INFO    MainThread:9504 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-13 19:32:25,138 INFO    MainThread:9504 [wandb_init.py:init():540] starting run threads in backend
2021-09-13 19:32:30,151 INFO    MainThread:9504 [wandb_run.py:_console_start():1601] atexit reg
2021-09-13 19:32:30,152 INFO    MainThread:9504 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-13 19:32:30,152 INFO    MainThread:9504 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-13 19:32:30,155 INFO    MainThread:9504 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-13 19:32:30,155 INFO    MainThread:9504 [wandb_init.py:init():565] run started, returning control to user process
2021-09-13 19:32:40,374 INFO    MainThread:9504 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-13 19:32:40,374 INFO    MainThread:9504 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-13 19:32:55,587 INFO    MainThread:9504 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-13 19:32:55,631 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:32:55,632 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:32:55,632 INFO    MainThread:9504 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210913_193255-1ok3gjo5\logs\debug.log
2021-09-13 19:32:55,632 INFO    MainThread:9504 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210913_193255-1ok3gjo5\logs\debug-internal.log
2021-09-13 19:32:55,633 INFO    MainThread:9504 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:32:55,633 INFO    MainThread:9504 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:32:55,646 INFO    MainThread:9504 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 22w7thw7
2021-09-13 19:32:55,646 INFO    MainThread:9504 [wandb_run.py:finish():1271] finishing run khushal/2final-weather-recognization/22w7thw7
