2021-09-13 19:50:34,564 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:50:34,564 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:50:34,565 INFO    MainThread:9504 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210913_195034-2nhlkkos\logs\debug.log
2021-09-13 19:50:34,565 INFO    MainThread:9504 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210913_195034-2nhlkkos\logs\debug-internal.log
2021-09-13 19:50:34,566 INFO    MainThread:9504 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D8990D53A0>
2021-09-13 19:50:34,599 INFO    MainThread:9504 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:50:34,599 INFO    MainThread:9504 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:50:34,599 INFO    MainThread:9504 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 2a5kiq6t
2021-09-13 19:50:34,599 INFO    MainThread:9504 [wandb_run.py:finish():1271] finishing run khushal/2final-weather-recognization/2a5kiq6t
2021-09-13 19:50:34,602 INFO    MainThread:9504 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-13 19:50:34,603 INFO    MainThread:9504 [wandb_run.py:_restore():1543] restore
2021-09-13 19:50:35,067 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 483
}

2021-09-13 19:50:35,729 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 483
}

2021-09-13 19:50:36,662 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21246
}

2021-09-13 19:50:36,764 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21246
}

2021-09-13 19:50:36,865 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21246
}

2021-09-13 19:50:36,966 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21246
}

2021-09-13 19:50:37,067 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21246
}

2021-09-13 19:50:37,172 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21246
}

2021-09-13 19:50:37,273 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21246
}

2021-09-13 19:50:37,375 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 21246
}

2021-09-13 19:50:37,476 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21246
  total_bytes: 21246
}

2021-09-13 19:50:37,577 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21246
  total_bytes: 21246
}

2021-09-13 19:50:37,679 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21246
  total_bytes: 21246
}

2021-09-13 19:50:37,781 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21246
  total_bytes: 21246
}

2021-09-13 19:50:37,883 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21246
  total_bytes: 21246
}

2021-09-13 19:50:37,985 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21246
  total_bytes: 21246
}

2021-09-13 19:50:38,087 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21246
  total_bytes: 21246
}

2021-09-13 19:50:39,313 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21246
  total_bytes: 21246
}

2021-09-13 19:50:39,414 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 21246
  total_bytes: 21246
}

2021-09-13 19:50:40,782 INFO    MainThread:9504 [wandb_run.py:_show_files():1915] logging synced files
2021-09-13 19:50:40,786 INFO    MainThread:9504 [wandb_init.py:init():424] starting backend
2021-09-13 19:50:40,786 INFO    MainThread:9504 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-13 19:50:40,791 INFO    MainThread:9504 [backend.py:ensure_launched():135] starting backend process...
2021-09-13 19:50:40,891 INFO    MainThread:9504 [backend.py:ensure_launched():139] started backend process with pid: 11548
2021-09-13 19:50:40,892 INFO    MainThread:9504 [wandb_init.py:init():429] backend started and connected
2021-09-13 19:50:40,893 INFO    MainThread:9504 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-13 19:50:40,893 INFO    MainThread:9504 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-13 19:50:40,893 INFO    MainThread:9504 [wandb_init.py:init():477] updated telemetry
2021-09-13 19:50:40,894 INFO    MainThread:9504 [wandb_init.py:init():500] communicating current version
2021-09-13 19:50:44,035 INFO    MainThread:9504 [wandb_init.py:init():505] got version response 
2021-09-13 19:50:44,036 INFO    MainThread:9504 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-13 19:50:44,775 INFO    MainThread:9504 [wandb_init.py:init():540] starting run threads in backend
2021-09-13 19:50:49,788 INFO    MainThread:9504 [wandb_run.py:_console_start():1601] atexit reg
2021-09-13 19:50:49,790 INFO    MainThread:9504 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-13 19:50:49,791 INFO    MainThread:9504 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-13 19:50:49,793 INFO    MainThread:9504 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-13 19:50:49,793 INFO    MainThread:9504 [wandb_init.py:init():565] run started, returning control to user process
2021-09-13 19:50:49,793 INFO    MainThread:9504 [wandb_config.py:__setitem__():141] config set epochs = 60 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001D8953B8F10>>
2021-09-13 19:50:49,793 INFO    MainThread:9504 [wandb_run.py:_config_callback():843] config_cb epochs 60 None
2021-09-13 19:50:49,794 INFO    MainThread:9504 [wandb_config.py:__setitem__():141] config set size = 128 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001D8953B8F10>>
2021-09-13 19:50:49,794 INFO    MainThread:9504 [wandb_run.py:_config_callback():843] config_cb size 128 None
2021-09-13 19:50:49,794 INFO    MainThread:9504 [wandb_config.py:__setitem__():141] config set dropout = 0.3 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001D8953B8F10>>
2021-09-13 19:50:49,794 INFO    MainThread:9504 [wandb_run.py:_config_callback():843] config_cb dropout 0.3 None
2021-09-13 19:50:49,794 INFO    MainThread:9504 [wandb_config.py:__setitem__():141] config set batch_size = 14 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001D8953B8F10>>
2021-09-13 19:50:49,795 INFO    MainThread:9504 [wandb_run.py:_config_callback():843] config_cb batch_size 14 None
2021-09-13 19:50:49,795 INFO    MainThread:9504 [wandb_config.py:__setitem__():141] config set pool_size = [4, 4] - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001D8953B8F10>>
2021-09-13 19:50:49,795 INFO    MainThread:9504 [wandb_run.py:_config_callback():843] config_cb pool_size [4, 4] None
2021-09-13 19:50:49,795 INFO    MainThread:9504 [wandb_config.py:__setitem__():141] config set shear_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001D8953B8F10>>
2021-09-13 19:50:49,795 INFO    MainThread:9504 [wandb_run.py:_config_callback():843] config_cb shear_range 0.4 None
2021-09-13 19:50:49,795 INFO    MainThread:9504 [wandb_config.py:__setitem__():141] config set zoom_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000001D8953B8F10>>
2021-09-13 19:50:49,796 INFO    MainThread:9504 [wandb_run.py:_config_callback():843] config_cb zoom_range 0.4 None
2021-09-13 19:51:00,009 INFO    MainThread:9504 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-13 19:51:00,010 INFO    MainThread:9504 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-13 19:52:19,999 INFO    MainThread:9504 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-13 19:52:20,112 INFO    MainThread:9504 [wandb_init.py:_pause_backend():256] pausing backend
2021-09-13 19:52:20,112 INFO    MainThread:9504 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-13 19:52:42,098 INFO    MainThread:9504 [wandb_init.py:_resume_backend():265] resuming backend
2021-09-13 19:52:42,167 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:52:42,167 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:52:42,168 INFO    MainThread:9504 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210913_195242-udvcey0q\logs\debug.log
2021-09-13 19:52:42,168 INFO    MainThread:9504 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210913_195242-udvcey0q\logs\debug-internal.log
2021-09-13 19:52:42,169 INFO    MainThread:9504 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:52:42,169 INFO    MainThread:9504 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:52:42,191 INFO    MainThread:9504 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 2nhlkkos
2021-09-13 19:52:42,191 INFO    MainThread:9504 [wandb_run.py:finish():1271] finishing run khushal/2final-weather-recognization/2nhlkkos
