2021-09-13 19:23:16,923 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:23:16,923 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:23:16,924 INFO    MainThread:9504 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210913_192316-e7isrkw7\logs\debug.log
2021-09-13 19:23:16,924 INFO    MainThread:9504 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210913_192316-e7isrkw7\logs\debug-internal.log
2021-09-13 19:23:16,925 INFO    MainThread:9504 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:23:16,925 INFO    MainThread:9504 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:23:16,947 INFO    MainThread:9504 [wandb_init.py:init():395] re-initializing run, found existing run on stack: hgyo5c8r
2021-09-13 19:23:16,947 INFO    MainThread:9504 [wandb_run.py:finish():1271] finishing run khushal/2final-weather-recognization/hgyo5c8r
2021-09-13 19:23:16,950 INFO    MainThread:9504 [jupyter.py:save_history():353] not saving jupyter history
2021-09-13 19:23:16,950 INFO    MainThread:9504 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-13 19:23:16,950 INFO    MainThread:9504 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-09-13 19:23:16,950 INFO    MainThread:9504 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-13 19:23:16,951 INFO    MainThread:9504 [wandb_run.py:_restore():1543] restore
2021-09-13 19:23:17,526 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 483
}

2021-09-13 19:23:18,842 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 483
}

2021-09-13 19:23:19,853 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 20967
}

2021-09-13 19:23:19,954 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 20967
}

2021-09-13 19:23:20,055 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 20967
}

2021-09-13 19:23:20,157 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 20967
}

2021-09-13 19:23:20,258 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 20967
}

2021-09-13 19:23:20,359 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 20967
}

2021-09-13 19:23:20,461 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 20967
}

2021-09-13 19:23:20,562 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 20967
}

2021-09-13 19:23:20,663 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 483
  total_bytes: 20967
}

2021-09-13 19:23:20,764 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 967
  total_bytes: 20967
}

2021-09-13 19:23:20,867 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:20,968 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:21,069 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:21,170 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:21,271 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:21,372 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:21,485 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:21,586 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:22,448 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:22,549 INFO    MainThread:9504 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20967
  total_bytes: 20967
}

2021-09-13 19:23:23,887 INFO    MainThread:9504 [wandb_run.py:_show_files():1915] logging synced files
2021-09-13 19:23:23,893 INFO    MainThread:9504 [wandb_init.py:init():424] starting backend
2021-09-13 19:23:23,893 INFO    MainThread:9504 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-13 19:23:23,897 INFO    MainThread:9504 [backend.py:ensure_launched():135] starting backend process...
2021-09-13 19:23:23,990 INFO    MainThread:9504 [backend.py:ensure_launched():139] started backend process with pid: 4588
2021-09-13 19:23:23,991 INFO    MainThread:9504 [wandb_init.py:init():429] backend started and connected
2021-09-13 19:23:23,992 INFO    MainThread:9504 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-13 19:23:23,992 INFO    MainThread:9504 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-13 19:23:23,992 INFO    MainThread:9504 [wandb_init.py:init():477] updated telemetry
2021-09-13 19:23:23,993 INFO    MainThread:9504 [wandb_init.py:init():500] communicating current version
2021-09-13 19:23:27,693 INFO    MainThread:9504 [wandb_init.py:init():505] got version response 
2021-09-13 19:23:27,693 INFO    MainThread:9504 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-13 19:23:28,334 INFO    MainThread:9504 [wandb_init.py:init():540] starting run threads in backend
2021-09-13 19:23:33,348 INFO    MainThread:9504 [wandb_run.py:_console_start():1601] atexit reg
2021-09-13 19:23:33,349 INFO    MainThread:9504 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-13 19:23:33,349 INFO    MainThread:9504 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-13 19:23:33,352 INFO    MainThread:9504 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-13 19:23:33,352 INFO    MainThread:9504 [wandb_init.py:init():565] run started, returning control to user process
2021-09-13 19:24:06,102 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting env: {}
2021-09-13 19:24:06,102 INFO    MainThread:9504 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-13 19:24:06,103 INFO    MainThread:9504 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210913_192406-nwhua81r\logs\debug.log
2021-09-13 19:24:06,103 INFO    MainThread:9504 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210913_192406-nwhua81r\logs\debug-internal.log
2021-09-13 19:24:06,104 INFO    MainThread:9504 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001D8861AFB20>
2021-09-13 19:24:06,141 INFO    MainThread:9504 [wandb_init.py:init():375] calling init triggers
2021-09-13 19:24:06,141 INFO    MainThread:9504 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-13 19:24:06,141 INFO    MainThread:9504 [wandb_init.py:init():395] re-initializing run, found existing run on stack: e7isrkw7
2021-09-13 19:24:06,141 INFO    MainThread:9504 [wandb_run.py:finish():1271] finishing run khushal/2final-weather-recognization/e7isrkw7
