2021-09-04 14:48:20,648 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting env: {}
2021-09-04 14:48:20,648 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:48:20,648 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:48:20,649 INFO    MainThread:24248 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210904_144820-e9wjig9g\logs\debug.log
2021-09-04 14:48:20,649 INFO    MainThread:24248 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210904_144820-e9wjig9g\logs\debug-internal.log
2021-09-04 14:48:20,650 INFO    MainThread:24248 [wandb_init.py:init():375] calling init triggers
2021-09-04 14:48:20,679 INFO    MainThread:24248 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-04 14:48:20,679 INFO    MainThread:24248 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 23jnvway
2021-09-04 14:48:20,680 INFO    MainThread:24248 [wandb_run.py:finish():1271] finishing run khushal/final-weather-recognization/23jnvway
2021-09-04 14:48:20,680 INFO    MainThread:24248 [jupyter.py:save_history():353] not saving jupyter history
2021-09-04 14:48:20,681 INFO    MainThread:24248 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-04 14:48:20,681 INFO    MainThread:24248 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-09-04 14:48:20,681 INFO    MainThread:24248 [wandb_run.py:_atexit_cleanup():1571] got exitcode: 0
2021-09-04 14:48:20,682 INFO    MainThread:24248 [wandb_run.py:_restore():1543] restore
2021-09-04 14:48:21,457 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:48:21,619 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:48:22,509 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:48:23,499 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20169
}

2021-09-04 14:48:23,600 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20169
}

2021-09-04 14:48:23,702 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20169
}

2021-09-04 14:48:23,803 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20169
}

2021-09-04 14:48:23,904 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20169
}

2021-09-04 14:48:24,005 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20169
}

2021-09-04 14:48:24,107 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20169
}

2021-09-04 14:48:24,208 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20169
}

2021-09-04 14:48:24,310 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 20169
}

2021-09-04 14:48:24,412 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20169
  total_bytes: 20169
}

2021-09-04 14:48:24,514 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20169
  total_bytes: 20169
}

2021-09-04 14:48:24,616 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20169
  total_bytes: 20169
}

2021-09-04 14:48:24,717 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20169
  total_bytes: 20169
}

2021-09-04 14:48:24,821 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20169
  total_bytes: 20169
}

2021-09-04 14:48:24,922 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20169
  total_bytes: 20169
}

2021-09-04 14:48:25,744 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20169
  total_bytes: 20169
}

2021-09-04 14:48:25,845 INFO    MainThread:24248 [wandb_run.py:_wait_for_finish():1693] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 20169
  total_bytes: 20169
}

2021-09-04 14:48:27,222 INFO    MainThread:24248 [wandb_run.py:_show_files():1915] logging synced files
2021-09-04 14:48:27,227 INFO    MainThread:24248 [wandb_init.py:init():424] starting backend
2021-09-04 14:48:27,227 INFO    MainThread:24248 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-04 14:48:27,232 INFO    MainThread:24248 [backend.py:ensure_launched():135] starting backend process...
2021-09-04 14:48:27,370 INFO    MainThread:24248 [backend.py:ensure_launched():139] started backend process with pid: 1632
2021-09-04 14:48:27,371 INFO    MainThread:24248 [wandb_init.py:init():429] backend started and connected
2021-09-04 14:48:27,372 INFO    MainThread:24248 [wandb_run.py:_label_probe_notebook():815] probe notebook
2021-09-04 14:48:27,372 INFO    MainThread:24248 [wandb_run.py:_label_probe_notebook():822] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-04 14:48:27,372 INFO    MainThread:24248 [wandb_init.py:init():477] updated telemetry
2021-09-04 14:48:27,373 INFO    MainThread:24248 [wandb_init.py:init():500] communicating current version
2021-09-04 14:48:31,672 INFO    MainThread:24248 [wandb_init.py:init():505] got version response 
2021-09-04 14:48:31,673 INFO    MainThread:24248 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-04 14:48:32,907 INFO    MainThread:24248 [wandb_init.py:init():540] starting run threads in backend
2021-09-04 14:48:37,922 INFO    MainThread:24248 [wandb_run.py:_console_start():1601] atexit reg
2021-09-04 14:48:37,924 INFO    MainThread:24248 [wandb_run.py:_redirect():1475] redirect: SettingsConsole.WRAP
2021-09-04 14:48:37,925 INFO    MainThread:24248 [wandb_run.py:_redirect():1512] Wrapping output streams.
2021-09-04 14:48:37,927 INFO    MainThread:24248 [wandb_run.py:_redirect():1536] Redirects installed.
2021-09-04 14:48:37,927 INFO    MainThread:24248 [wandb_init.py:init():565] run started, returning control to user process
2021-09-04 14:50:40,181 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting env: {}
2021-09-04 14:50:40,182 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:50:40,182 INFO    MainThread:24248 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:50:40,182 INFO    MainThread:24248 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210904_145040-1gjkk0p2\logs\debug.log
2021-09-04 14:50:40,182 INFO    MainThread:24248 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210904_145040-1gjkk0p2\logs\debug-internal.log
2021-09-04 14:50:40,183 INFO    MainThread:24248 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000023AB5504BB0>
2021-09-04 14:50:40,211 INFO    MainThread:24248 [wandb_init.py:init():375] calling init triggers
2021-09-04 14:50:40,212 INFO    MainThread:24248 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-04 14:50:40,212 INFO    MainThread:24248 [wandb_init.py:init():395] re-initializing run, found existing run on stack: e9wjig9g
2021-09-04 14:50:40,212 INFO    MainThread:24248 [wandb_run.py:finish():1271] finishing run khushal/final-weather-recognization/e9wjig9g
