2021-08-18 11:23:22,713 INFO    MainThread:5372 [wandb_setup.py:_flush():69] setting env: {}
2021-08-18 11:23:22,728 INFO    MainThread:5372 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-18 11:23:22,728 INFO    MainThread:5372 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210818_112322-hzqxpw1n\logs\debug.log
2021-08-18 11:23:22,728 INFO    MainThread:5372 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210818_112322-hzqxpw1n\logs\debug-internal.log
2021-08-18 11:23:22,728 INFO    MainThread:5372 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000174ABE27700>
2021-08-18 11:23:22,728 INFO    MainThread:5372 [wandb_init.py:init():375] calling init triggers
2021-08-18 11:23:22,728 INFO    MainThread:5372 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-18 11:23:22,728 INFO    MainThread:5372 [wandb_init.py:init():424] starting backend
2021-08-18 11:23:22,728 INFO    MainThread:5372 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-18 11:23:22,744 INFO    MainThread:5372 [backend.py:ensure_launched():135] starting backend process...
2021-08-18 11:23:23,009 INFO    MainThread:5372 [backend.py:ensure_launched():139] started backend process with pid: 492
2021-08-18 11:23:23,009 INFO    MainThread:5372 [wandb_init.py:init():429] backend started and connected
2021-08-18 11:23:23,009 INFO    MainThread:5372 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-18 11:23:23,009 INFO    MainThread:5372 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-18 11:23:23,009 INFO    MainThread:5372 [wandb_init.py:init():477] updated telemetry
2021-08-18 11:23:23,009 INFO    MainThread:5372 [wandb_init.py:init():500] communicating current version
2021-08-18 11:23:28,012 INFO    MainThread:5372 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-18 11:23:29,746 INFO    MainThread:5372 [wandb_init.py:init():540] starting run threads in backend
2021-08-18 11:23:34,778 INFO    MainThread:5372 [wandb_run.py:_console_start():1584] atexit reg
2021-08-18 11:23:34,809 INFO    MainThread:5372 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-18 11:23:34,809 INFO    MainThread:5372 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-18 11:23:34,809 INFO    MainThread:5372 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-18 11:23:34,824 INFO    MainThread:5372 [wandb_init.py:init():565] run started, returning control to user process
2021-08-18 11:23:34,824 INFO    MainThread:5372 [wandb_config.py:__setitem__():141] config set epochs = 50 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x00000174ADC14280>>
2021-08-18 11:23:34,824 INFO    MainThread:5372 [wandb_run.py:_config_callback():826] config_cb epochs 50 None
2021-08-18 11:26:42,679 INFO    MainThread:5372 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-18 11:26:42,679 INFO    MainThread:5372 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-18 11:34:32,795 INFO    MainThread:5372 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-18 11:34:32,795 INFO    MainThread:5372 [wandb_run.py:_restore():1526] restore
