2021-09-03 19:06:00,427 INFO    MainThread:14380 [wandb_setup.py:_flush():69] setting env: {}
2021-09-03 19:06:00,428 INFO    MainThread:14380 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-03 19:06:00,428 INFO    MainThread:14380 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-03 19:06:00,429 INFO    MainThread:14380 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210903_190600-sz0y7kt5\logs\debug.log
2021-09-03 19:06:00,429 INFO    MainThread:14380 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210903_190600-sz0y7kt5\logs\debug-internal.log
2021-09-03 19:06:00,430 INFO    MainThread:14380 [wandb_init.py:init():375] calling init triggers
2021-09-03 19:06:00,431 INFO    MainThread:14380 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-03 19:06:00,432 INFO    MainThread:14380 [wandb_init.py:init():395] re-initializing run, found existing run on stack: qdx4cxg9
2021-09-03 19:06:00,432 INFO    MainThread:14380 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/qdx4cxg9
2021-09-03 19:06:00,433 INFO    MainThread:14380 [jupyter.py:save_history():339] not saving jupyter history
2021-09-03 19:06:00,433 INFO    MainThread:14380 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-09-03 19:06:00,434 INFO    MainThread:14380 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-09-03 19:06:00,434 INFO    MainThread:14380 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-09-03 19:06:00,435 INFO    MainThread:14380 [wandb_run.py:_restore():1526] restore
2021-09-03 19:06:00,756 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-03 19:06:00,941 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-03 19:06:01,873 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-03 19:06:02,234 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19839
}

2021-09-03 19:06:02,338 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:02,441 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:02,546 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:02,657 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:02,759 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:02,862 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:02,965 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:03,069 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:03,172 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:03,275 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:03,387 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:03,502 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19866
}

2021-09-03 19:06:03,612 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 15347
  total_bytes: 19866
}

2021-09-03 19:06:03,716 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19866
  total_bytes: 19866
}

2021-09-03 19:06:03,820 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19866
  total_bytes: 19866
}

2021-09-03 19:06:03,944 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19866
  total_bytes: 19866
}

2021-09-03 19:06:04,056 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19866
  total_bytes: 19866
}

2021-09-03 19:06:04,162 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19866
  total_bytes: 19866
}

2021-09-03 19:06:04,266 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19866
  total_bytes: 19866
}

2021-09-03 19:06:04,370 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19866
  total_bytes: 19866
}

2021-09-03 19:06:05,551 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19866
  total_bytes: 19866
}

2021-09-03 19:06:05,656 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19866
  total_bytes: 19866
}

2021-09-03 19:06:07,576 INFO    MainThread:14380 [wandb_run.py:_show_files():1898] logging synced files
2021-09-03 19:06:07,833 INFO    MainThread:14380 [wandb_init.py:init():424] starting backend
2021-09-03 19:06:07,834 INFO    MainThread:14380 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-03 19:06:07,846 INFO    MainThread:14380 [backend.py:ensure_launched():135] starting backend process...
2021-09-03 19:06:11,194 INFO    MainThread:14380 [backend.py:ensure_launched():139] started backend process with pid: 20880
2021-09-03 19:06:11,196 INFO    MainThread:14380 [wandb_init.py:init():429] backend started and connected
2021-09-03 19:06:11,198 INFO    MainThread:14380 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-09-03 19:06:11,198 INFO    MainThread:14380 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-03 19:06:11,198 INFO    MainThread:14380 [wandb_init.py:init():477] updated telemetry
2021-09-03 19:06:11,200 INFO    MainThread:14380 [wandb_init.py:init():500] communicating current version
2021-09-03 19:06:16,202 INFO    MainThread:14380 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-03 19:06:19,704 INFO    MainThread:14380 [wandb_init.py:init():540] starting run threads in backend
2021-09-03 19:06:24,737 INFO    MainThread:14380 [wandb_run.py:_console_start():1584] atexit reg
2021-09-03 19:06:24,791 INFO    MainThread:14380 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-09-03 19:06:24,792 INFO    MainThread:14380 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-09-03 19:06:24,798 INFO    MainThread:14380 [wandb_run.py:_redirect():1519] Redirects installed.
2021-09-03 19:06:24,799 INFO    MainThread:14380 [wandb_init.py:init():565] run started, returning control to user process
2021-09-03 19:06:24,800 INFO    MainThread:14380 [wandb_config.py:__setitem__():141] config set epochs = 60 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000024162DA62B0>>
2021-09-03 19:06:24,800 INFO    MainThread:14380 [wandb_run.py:_config_callback():826] config_cb epochs 60 None
2021-09-03 19:06:24,801 INFO    MainThread:14380 [wandb_config.py:__setitem__():141] config set size = 128 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000024162DA62B0>>
2021-09-03 19:06:24,802 INFO    MainThread:14380 [wandb_run.py:_config_callback():826] config_cb size 128 None
2021-09-03 19:06:24,803 INFO    MainThread:14380 [wandb_config.py:__setitem__():141] config set dropout = 0.3 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000024162DA62B0>>
2021-09-03 19:06:24,803 INFO    MainThread:14380 [wandb_run.py:_config_callback():826] config_cb dropout 0.3 None
2021-09-03 19:06:24,804 INFO    MainThread:14380 [wandb_config.py:__setitem__():141] config set batch_size = 14 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000024162DA62B0>>
2021-09-03 19:06:24,805 INFO    MainThread:14380 [wandb_run.py:_config_callback():826] config_cb batch_size 14 None
2021-09-03 19:06:24,806 INFO    MainThread:14380 [wandb_config.py:__setitem__():141] config set pool_size = [3, 3] - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000024162DA62B0>>
2021-09-03 19:06:24,806 INFO    MainThread:14380 [wandb_run.py:_config_callback():826] config_cb pool_size [3, 3] None
2021-09-03 19:06:24,808 INFO    MainThread:14380 [wandb_config.py:__setitem__():141] config set shear_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000024162DA62B0>>
2021-09-03 19:06:24,808 INFO    MainThread:14380 [wandb_run.py:_config_callback():826] config_cb shear_range 0.4 None
2021-09-03 19:06:24,809 INFO    MainThread:14380 [wandb_config.py:__setitem__():141] config set zoom_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x0000024162DA62B0>>
2021-09-03 19:06:24,810 INFO    MainThread:14380 [wandb_run.py:_config_callback():826] config_cb zoom_range 0.4 None
2021-09-03 19:08:56,593 INFO    MainThread:14380 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-09-03 19:08:56,594 INFO    MainThread:14380 [wandb_run.py:_restore():1526] restore
2021-09-03 19:08:57,154 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-03 19:08:57,768 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-03 19:08:58,722 INFO    MainThread:14380 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

