2021-08-18 14:56:00,859 INFO    MainThread:10184 [internal.py:wandb_internal():86] W&B internal server running at pid: 10184, started at: 2021-08-18 14:56:00.846725
2021-08-18 14:56:00,863 INFO    WriterThread:10184 [datastore.py:open_for_write():77] open: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\run-1bq5qy91.wandb
2021-08-18 14:56:00,864 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: check_version
2021-08-18 14:56:00,869 DEBUG   SenderThread:10184 [sender.py:send():182] send: header
2021-08-18 14:56:00,869 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: check_version
2021-08-18 14:56:01,937 DEBUG   SenderThread:10184 [sender.py:send():182] send: run
2021-08-18 14:56:02,632 INFO    SenderThread:10184 [dir_watcher.py:__init__():168] watching files in: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files
2021-08-18 14:56:02,632 INFO    SenderThread:10184 [sender.py:_start_run_threads():740] run started: 1bq5qy91 with start time 1629278758
2021-08-18 14:56:02,632 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: run_start
2021-08-18 14:56:02,633 DEBUG   SenderThread:10184 [sender.py:send():182] send: summary
2021-08-18 14:56:02,635 INFO    SenderThread:10184 [sender.py:_save_file():873] saving file wandb-summary.json with policy end
2021-08-18 14:56:03,636 INFO    Thread-8  :10184 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files\wandb-summary.json
2021-08-18 14:56:06,682 DEBUG   HandlerThread:10184 [meta.py:__init__():39] meta init
2021-08-18 14:56:06,682 DEBUG   HandlerThread:10184 [meta.py:__init__():53] meta init done
2021-08-18 14:56:06,682 DEBUG   HandlerThread:10184 [meta.py:probe():210] probe
2021-08-18 14:56:07,169 DEBUG   HandlerThread:10184 [meta.py:_save_pip():57] save pip
2021-08-18 14:56:07,214 DEBUG   HandlerThread:10184 [meta.py:_save_pip():71] save pip done
2021-08-18 14:56:07,215 DEBUG   HandlerThread:10184 [meta.py:_save_conda():78] save conda
2021-08-18 14:56:07,649 INFO    Thread-8  :10184 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files\conda-environment.yaml
2021-08-18 14:56:07,650 INFO    Thread-8  :10184 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files\requirements.txt
2021-08-18 14:56:08,650 INFO    Thread-8  :10184 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files\output.log
2021-08-18 14:56:10,651 INFO    Thread-8  :10184 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files\output.log
2021-08-18 14:56:26,665 INFO    Thread-8  :10184 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files\conda-environment.yaml
2021-08-18 14:56:26,699 DEBUG   HandlerThread:10184 [meta.py:_save_conda():86] save conda done
2021-08-18 14:56:26,700 DEBUG   HandlerThread:10184 [meta.py:probe():252] probe done
2021-08-18 14:56:26,708 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:56:26,708 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:56:26,714 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: get_summary
2021-08-18 14:56:27,363 DEBUG   SenderThread:10184 [sender.py:send():182] send: config
2021-08-18 14:56:27,363 DEBUG   SenderThread:10184 [sender.py:send():182] send: files
2021-08-18 14:56:27,364 INFO    SenderThread:10184 [sender.py:_save_file():873] saving file model-best.h5 with policy live
2021-08-18 14:56:27,364 DEBUG   SenderThread:10184 [sender.py:send():182] send: files
2021-08-18 14:56:27,366 INFO    SenderThread:10184 [sender.py:_save_file():873] saving file wandb-metadata.json with policy now
2021-08-18 14:56:27,666 INFO    Thread-8  :10184 [dir_watcher.py:_on_file_created():216] file/dir created: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files\wandb-metadata.json
2021-08-18 14:56:28,857 INFO    Thread-11 :10184 [upload_job.py:push():137] Uploaded file C:\Users\HP\AppData\Local\Temp\tmp9gdkddxpwandb\3s81ena5-wandb-metadata.json
2021-08-18 14:56:32,673 INFO    Thread-8  :10184 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files\config.yaml
2021-08-18 14:56:38,170 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 14:56:42,365 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:56:42,365 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:56:57,938 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:56:57,938 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:57:11,148 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 14:57:13,439 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:57:13,440 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:57:28,994 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:57:28,994 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:57:44,149 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 14:57:44,523 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:57:44,523 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:58:00,363 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:58:00,363 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:58:16,196 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:58:16,196 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:58:17,276 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 14:58:31,814 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:58:31,815 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:58:47,676 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:58:47,677 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:58:50,787 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 14:59:03,555 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:59:03,556 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:59:19,241 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:59:19,242 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:59:24,031 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 14:59:34,919 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:59:34,919 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:59:50,509 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 14:59:50,509 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 14:59:57,143 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:00:06,281 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:00:06,284 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:00:21,798 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:00:21,798 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:00:30,215 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:00:37,481 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:00:37,481 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:00:54,454 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:00:54,455 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:01:03,273 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:01:10,095 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:01:10,095 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:01:25,639 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:01:25,639 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:01:36,293 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:01:41,442 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:01:41,443 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:01:57,123 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:01:57,124 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:02:09,241 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:02:12,685 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:02:12,685 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:02:28,355 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:02:28,355 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:02:42,225 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:02:44,022 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:02:44,022 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:02:59,715 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:02:59,715 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:03:15,394 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:03:15,394 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:03:16,072 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:03:31,075 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:03:31,075 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:03:46,647 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:03:46,648 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:03:48,659 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:04:02,440 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:04:02,440 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:04:18,273 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:04:18,274 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:04:21,789 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:04:33,953 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:04:33,953 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:04:49,635 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:04:49,635 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:04:54,861 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:05:05,170 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:05:05,171 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:05:20,724 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:05:20,724 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:05:27,926 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:05:36,364 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:05:36,364 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:05:52,044 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:05:52,044 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:06:00,927 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:06:07,754 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:06:07,755 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:06:23,395 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:06:23,396 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:06:33,968 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:06:39,053 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:06:39,053 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:06:54,754 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:06:54,755 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:07:07,416 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:07:10,437 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:07:10,438 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:07:26,112 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:07:26,113 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:07:40,400 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:07:41,798 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:07:41,799 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:07:57,418 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:07:57,419 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:08:12,978 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:08:12,979 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:08:13,673 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:08:28,676 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:08:28,676 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:08:44,207 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:08:44,208 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:08:46,322 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:08:59,873 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:08:59,874 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:09:15,561 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:09:15,562 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:09:19,264 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:09:31,233 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:09:31,234 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:09:46,925 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:09:46,925 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:09:52,181 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:10:02,609 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:10:02,609 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:10:18,137 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:10:18,137 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:10:25,243 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:10:33,793 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:10:33,793 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:10:49,313 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:10:49,313 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:10:58,246 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:11:04,877 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:11:04,878 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:11:20,673 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:11:20,673 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:11:31,329 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:11:36,361 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:11:36,361 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:11:51,880 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:11:51,880 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:12:04,653 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:12:07,555 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:12:07,555 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:12:23,071 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:12:23,071 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:12:37,580 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:12:38,757 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:12:38,757 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:12:54,427 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:12:54,428 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:13:10,110 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:13:10,110 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:13:10,791 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:13:25,793 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:13:25,793 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:13:41,467 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:13:41,468 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:13:43,730 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:13:57,073 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:13:57,073 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:14:12,706 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:14:12,707 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:14:16,697 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:14:28,347 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:14:28,347 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:14:43,872 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:14:43,873 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:14:50,047 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:14:59,547 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:14:59,548 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:15:15,227 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:15:15,228 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:15:22,979 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:15:30,832 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:15:30,833 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:15:46,430 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:15:46,430 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:15:55,950 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:16:02,116 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:16:02,116 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:16:17,713 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:16:17,713 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:16:28,881 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:16:33,476 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:16:33,477 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:16:49,154 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:16:49,154 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:17:01,814 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:17:04,827 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:17:04,828 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:17:20,513 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:17:20,513 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:17:34,802 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:17:36,131 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:17:36,132 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:17:51,689 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:17:51,689 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:18:07,395 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:18:07,395 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:18:07,927 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:18:22,928 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:18:22,929 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:18:38,485 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:18:38,486 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:18:40,877 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:18:54,029 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:18:54,030 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:19:09,628 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:19:09,628 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:19:14,327 DEBUG   SenderThread:10184 [sender.py:send():182] send: stats
2021-08-18 15:19:25,314 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: stop_status
2021-08-18 15:19:25,315 DEBUG   SenderThread:10184 [sender.py:send_request():196] send_request: stop_status
2021-08-18 15:19:28,699 ERROR   SenderThread:10184 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\HP\anaconda3\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001687F1816D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\HP\anaconda3\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F1816D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\sdk\internal\internal_api.py", line 130, in execute
    return self.client.execute(*args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\vendor\gql-0.2.0\gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\wandb\vendor\gql-0.2.0\gql\transport\requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F1816D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2021-08-18 15:20:14,093 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None)). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:20:16,500 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F188250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:20:20,723 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F188A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:20:29,860 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F1888E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:20:48,830 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F188A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:21:24,929 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F04CE50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:22:31,550 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F04CE20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:24:52,571 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687DDD6D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:29:36,375 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687DDD6D30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:35:11,396 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687DDD6D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:40:18,872 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F002C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:45:33,370 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F002BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:50:41,002 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687DDD6310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 15:56:50,653 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687DDD6610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 16:02:51,176 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687DDD6430>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 16:08:55,785 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687DDD6610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 16:14:51,715 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687F002A90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
2021-08-18 16:17:17,144 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:17:17,532 INFO    Thread-8  :10184 [dir_watcher.py:_on_file_modified():229] file/dir modified: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\files\output.log
2021-08-18 16:17:22,243 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:17:27,343 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:17:32,444 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:17:37,544 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:17:42,645 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:17:47,746 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:17:52,848 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:17:57,947 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:03,049 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:08,153 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:13,250 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:18,350 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:23,450 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:28,551 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:33,651 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:38,751 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:43,853 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:48,953 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:54,054 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:18:59,154 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:04,254 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:09,353 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:14,455 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:19,558 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:24,658 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:29,759 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:34,860 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:39,960 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:45,061 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:50,160 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:19:55,261 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:00,362 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:05,463 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:10,562 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:15,664 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:20,764 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:25,866 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:30,967 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:36,067 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:41,169 DEBUG   HandlerThread:10184 [handler.py:handle_request():128] handle_request: poll_exit
2021-08-18 16:20:52,852 WARNING MainThread:10184 [internal.py:is_dead():364] Internal process exiting, parent pid 11196 disappeared
2021-08-18 16:20:52,853 ERROR   MainThread:10184 [internal.py:wandb_internal():141] Internal process shutdown.
2021-08-18 16:20:53,174 INFO    HandlerThread:10184 [handler.py:finish():677] shutting down handler
2021-08-18 16:20:53,724 INFO    WriterThread:10184 [datastore.py:close():281] close: F:\5th sem project\wandb\run-20210818_145552-1bq5qy91\run-1bq5qy91.wandb
2021-08-18 16:20:54,903 WARNING FileStreamThread:10184 [file_stream.py:request_with_retry():461] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/khushal/weather-recognization/1bq5qy91/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001687DDD6970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')). func: <bound method Session.post of <requests.sessions.Session object at 0x0000016877AD5130>>, args: ('https://api.wandb.ai/files/khushal/weather-recognization/1bq5qy91/file_stream',), kwargs: {'json': {'complete': False, 'failed': False, 'dropped': 0, 'uploaded': []}}
