2021-09-04 14:20:21,132 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting env: {}
2021-09-04 14:20:21,133 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:20:21,133 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:20:21,133 INFO    MainThread:2968 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210904_142021-3s4c3zz6\logs\debug.log
2021-09-04 14:20:21,134 INFO    MainThread:2968 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210904_142021-3s4c3zz6\logs\debug-internal.log
2021-09-04 14:20:21,135 INFO    MainThread:2968 [wandb_init.py:init():375] calling init triggers
2021-09-04 14:20:21,175 INFO    MainThread:2968 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-04 14:20:21,175 INFO    MainThread:2968 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 1er2bmeq
2021-09-04 14:20:21,176 INFO    MainThread:2968 [wandb_run.py:finish():1254] finishing run khushal/final-weather-recognization/1er2bmeq
2021-09-04 14:20:21,176 INFO    MainThread:2968 [jupyter.py:save_history():339] not saving jupyter history
2021-09-04 14:20:21,176 INFO    MainThread:2968 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-09-04 14:20:21,177 INFO    MainThread:2968 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-09-04 14:20:21,177 INFO    MainThread:2968 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-09-04 14:20:21,177 INFO    MainThread:2968 [wandb_run.py:_restore():1526] restore
2021-09-04 14:20:21,708 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:20:22,049 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:20:22,603 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 476
}

2021-09-04 14:20:22,708 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19687
}

2021-09-04 14:20:22,809 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19687
}

2021-09-04 14:20:22,910 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19687
}

2021-09-04 14:20:23,011 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19687
}

2021-09-04 14:20:23,112 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19687
}

2021-09-04 14:20:23,214 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19687
}

2021-09-04 14:20:23,315 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19687
}

2021-09-04 14:20:23,417 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 476
  total_bytes: 19687
}

2021-09-04 14:20:23,518 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19687
  total_bytes: 19687
}

2021-09-04 14:20:23,619 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19687
  total_bytes: 19687
}

2021-09-04 14:20:23,720 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19687
  total_bytes: 19687
}

2021-09-04 14:20:23,821 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19687
  total_bytes: 19687
}

2021-09-04 14:20:23,922 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19687
  total_bytes: 19687
}

2021-09-04 14:20:24,024 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19687
  total_bytes: 19687
}

2021-09-04 14:20:24,126 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19687
  total_bytes: 19687
}

2021-09-04 14:20:24,918 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19687
  total_bytes: 19687
}

2021-09-04 14:20:25,019 INFO    MainThread:2968 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19687
  total_bytes: 19687
}

2021-09-04 14:20:26,356 INFO    MainThread:2968 [wandb_run.py:_show_files():1898] logging synced files
2021-09-04 14:20:26,362 INFO    MainThread:2968 [wandb_init.py:init():424] starting backend
2021-09-04 14:20:26,363 INFO    MainThread:2968 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-09-04 14:20:26,368 INFO    MainThread:2968 [backend.py:ensure_launched():135] starting backend process...
2021-09-04 14:20:26,492 INFO    MainThread:2968 [backend.py:ensure_launched():139] started backend process with pid: 21728
2021-09-04 14:20:26,493 INFO    MainThread:2968 [wandb_init.py:init():429] backend started and connected
2021-09-04 14:20:26,494 INFO    MainThread:2968 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-09-04 14:20:26,494 INFO    MainThread:2968 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-04 14:20:26,494 INFO    MainThread:2968 [wandb_init.py:init():477] updated telemetry
2021-09-04 14:20:26,495 INFO    MainThread:2968 [wandb_init.py:init():500] communicating current version
2021-09-04 14:20:30,889 INFO    MainThread:2968 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.1 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-09-04 14:20:30,890 INFO    MainThread:2968 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-09-04 14:20:31,520 INFO    MainThread:2968 [wandb_init.py:init():540] starting run threads in backend
2021-09-04 14:20:36,533 INFO    MainThread:2968 [wandb_run.py:_console_start():1584] atexit reg
2021-09-04 14:20:36,534 INFO    MainThread:2968 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-09-04 14:20:36,535 INFO    MainThread:2968 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-09-04 14:20:36,537 INFO    MainThread:2968 [wandb_run.py:_redirect():1519] Redirects installed.
2021-09-04 14:20:36,537 INFO    MainThread:2968 [wandb_init.py:init():565] run started, returning control to user process
2021-09-04 14:22:04,091 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting env: {}
2021-09-04 14:22:04,091 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:22:04,091 INFO    MainThread:2968 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-04 14:22:04,092 INFO    MainThread:2968 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210904_142204-3d0tgi1n\logs\debug.log
2021-09-04 14:22:04,092 INFO    MainThread:2968 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210904_142204-3d0tgi1n\logs\debug-internal.log
2021-09-04 14:22:04,093 INFO    MainThread:2968 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001FA43B597C0>
2021-09-04 14:22:04,120 INFO    MainThread:2968 [wandb_init.py:init():375] calling init triggers
2021-09-04 14:22:04,120 INFO    MainThread:2968 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-09-04 14:22:04,120 INFO    MainThread:2968 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3s4c3zz6
2021-09-04 14:22:04,121 INFO    MainThread:2968 [wandb_run.py:finish():1254] finishing run khushal/final-weather-recognization/3s4c3zz6
