2021-08-23 17:37:06,889 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting env: {}
2021-08-23 17:37:06,890 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-23 17:37:06,890 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-23 17:37:06,891 INFO    MainThread:12104 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210823_173706-3m74sbqx\logs\debug.log
2021-08-23 17:37:06,893 INFO    MainThread:12104 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210823_173706-3m74sbqx\logs\debug-internal.log
2021-08-23 17:37:06,895 INFO    MainThread:12104 [wandb_init.py:init():375] calling init triggers
2021-08-23 17:37:06,901 INFO    MainThread:12104 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-23 17:37:06,901 INFO    MainThread:12104 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 1i8zl0at
2021-08-23 17:37:06,902 INFO    MainThread:12104 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/1i8zl0at
2021-08-23 17:37:06,902 INFO    MainThread:12104 [jupyter.py:save_history():339] not saving jupyter history
2021-08-23 17:37:06,903 INFO    MainThread:12104 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-23 17:37:06,903 INFO    MainThread:12104 [wandb_init.py:_jupyter_teardown():275] cleaning up jupyter logic
2021-08-23 17:37:06,903 INFO    MainThread:12104 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-23 17:37:06,905 INFO    MainThread:12104 [wandb_run.py:_restore():1526] restore
2021-08-23 17:37:07,580 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-23 17:37:07,748 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-23 17:37:08,689 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-23 17:37:09,219 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:09,322 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:09,427 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:09,531 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:09,634 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:09,740 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:09,844 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:09,948 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:10,053 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:10,180 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:10,285 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:10,389 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:10,492 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:37:10,597 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13948
  total_bytes: 19764
}

2021-08-23 17:37:10,700 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:10,805 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:10,909 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:11,013 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:11,117 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:11,221 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:11,326 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:11,429 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:12,559 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:12,663 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:37:14,475 INFO    MainThread:12104 [wandb_run.py:_show_files():1898] logging synced files
2021-08-23 17:37:14,492 INFO    MainThread:12104 [wandb_init.py:init():424] starting backend
2021-08-23 17:37:14,492 INFO    MainThread:12104 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-23 17:37:14,501 INFO    MainThread:12104 [backend.py:ensure_launched():135] starting backend process...
2021-08-23 17:37:14,765 INFO    MainThread:12104 [backend.py:ensure_launched():139] started backend process with pid: 17824
2021-08-23 17:37:14,767 INFO    MainThread:12104 [wandb_init.py:init():429] backend started and connected
2021-08-23 17:37:14,768 INFO    MainThread:12104 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-23 17:37:14,769 INFO    MainThread:12104 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-23 17:37:14,769 INFO    MainThread:12104 [wandb_init.py:init():477] updated telemetry
2021-08-23 17:37:14,770 INFO    MainThread:12104 [wandb_init.py:init():500] communicating current version
2021-08-23 17:37:19,772 INFO    MainThread:12104 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-23 17:37:22,508 INFO    MainThread:12104 [wandb_init.py:init():540] starting run threads in backend
2021-08-23 17:37:27,559 INFO    MainThread:12104 [wandb_run.py:_console_start():1584] atexit reg
2021-08-23 17:37:27,561 INFO    MainThread:12104 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-23 17:37:27,562 INFO    MainThread:12104 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-23 17:37:27,567 INFO    MainThread:12104 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-23 17:37:27,567 INFO    MainThread:12104 [wandb_init.py:init():565] run started, returning control to user process
2021-08-23 17:37:27,568 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set epochs = 5 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033D0E5B0>>
2021-08-23 17:37:27,568 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb epochs 5 None
2021-08-23 17:37:27,569 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set size = 128 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033D0E5B0>>
2021-08-23 17:37:27,570 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb size 128 None
2021-08-23 17:37:27,571 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set dropout = 0.3 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033D0E5B0>>
2021-08-23 17:37:27,571 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb dropout 0.3 None
2021-08-23 17:37:27,572 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set batch_size = 14 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033D0E5B0>>
2021-08-23 17:37:27,572 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb batch_size 14 None
2021-08-23 17:37:27,573 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set pool_size = [3, 3] - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033D0E5B0>>
2021-08-23 17:37:27,573 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb pool_size [3, 3] None
2021-08-23 17:37:27,574 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set shear_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033D0E5B0>>
2021-08-23 17:37:27,574 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb shear_range 0.4 None
2021-08-23 17:37:27,575 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set zoom_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033D0E5B0>>
2021-08-23 17:37:27,575 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb zoom_range 0.4 None
2021-08-23 17:37:30,082 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting env: {}
2021-08-23 17:37:30,083 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-23 17:37:30,083 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-23 17:37:30,084 INFO    MainThread:12104 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210823_173730-1w261qvj\logs\debug.log
2021-08-23 17:37:30,084 INFO    MainThread:12104 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210823_173730-1w261qvj\logs\debug-internal.log
2021-08-23 17:37:30,086 INFO    MainThread:12104 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002A033C7E880>
2021-08-23 17:37:30,105 INFO    MainThread:12104 [wandb_init.py:init():375] calling init triggers
2021-08-23 17:37:30,105 INFO    MainThread:12104 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-23 17:37:30,105 INFO    MainThread:12104 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 3m74sbqx
2021-08-23 17:37:30,106 INFO    MainThread:12104 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/3m74sbqx
