2021-08-23 17:33:29,334 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting env: {}
2021-08-23 17:33:29,335 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-23 17:33:29,335 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-23 17:33:29,335 INFO    MainThread:12104 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210823_173329-1z8qljtr\logs\debug.log
2021-08-23 17:33:29,336 INFO    MainThread:12104 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210823_173329-1z8qljtr\logs\debug-internal.log
2021-08-23 17:33:29,337 INFO    MainThread:12104 [wandb_init.py:_jupyter_setup():294] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002A033C7EDF0>
2021-08-23 17:33:29,345 INFO    MainThread:12104 [wandb_init.py:init():375] calling init triggers
2021-08-23 17:33:29,346 INFO    MainThread:12104 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-23 17:33:29,346 INFO    MainThread:12104 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 2fq03hxv
2021-08-23 17:33:29,346 INFO    MainThread:12104 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/2fq03hxv
2021-08-23 17:33:29,347 INFO    MainThread:12104 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 0
2021-08-23 17:33:29,347 INFO    MainThread:12104 [wandb_run.py:_restore():1526] restore
2021-08-23 17:33:29,513 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-23 17:33:29,631 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-23 17:33:30,691 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 484
}

2021-08-23 17:33:31,138 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:31,241 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:31,345 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:31,448 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:31,552 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:31,655 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:31,759 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:31,864 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:31,987 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:32,091 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:32,195 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 484
  total_bytes: 19764
}

2021-08-23 17:33:32,366 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13159
  total_bytes: 19764
}

2021-08-23 17:33:32,470 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13159
  total_bytes: 19764
}

2021-08-23 17:33:32,575 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13186
  total_bytes: 19764
}

2021-08-23 17:33:32,678 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 13186
  total_bytes: 19764
}

2021-08-23 17:33:32,782 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19102
  total_bytes: 19764
}

2021-08-23 17:33:32,885 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19102
  total_bytes: 19764
}

2021-08-23 17:33:32,990 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:33,092 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:33,200 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:33,311 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:33,413 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:33,518 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:33,622 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:33,725 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:34,446 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:34,551 INFO    MainThread:12104 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 19764
  total_bytes: 19764
}

2021-08-23 17:33:36,314 INFO    MainThread:12104 [wandb_run.py:_show_files():1898] logging synced files
2021-08-23 17:33:36,323 INFO    MainThread:12104 [wandb_init.py:init():424] starting backend
2021-08-23 17:33:36,324 INFO    MainThread:12104 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-08-23 17:33:36,332 INFO    MainThread:12104 [backend.py:ensure_launched():135] starting backend process...
2021-08-23 17:33:36,605 INFO    MainThread:12104 [backend.py:ensure_launched():139] started backend process with pid: 3684
2021-08-23 17:33:36,607 INFO    MainThread:12104 [wandb_init.py:init():429] backend started and connected
2021-08-23 17:33:36,609 INFO    MainThread:12104 [wandb_run.py:_label_probe_notebook():798] probe notebook
2021-08-23 17:33:36,609 INFO    MainThread:12104 [wandb_run.py:_label_probe_notebook():805] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-08-23 17:33:36,609 INFO    MainThread:12104 [wandb_init.py:init():477] updated telemetry
2021-08-23 17:33:36,611 INFO    MainThread:12104 [wandb_init.py:init():500] communicating current version
2021-08-23 17:33:41,612 INFO    MainThread:12104 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-08-23 17:33:43,580 INFO    MainThread:12104 [wandb_init.py:init():540] starting run threads in backend
2021-08-23 17:33:48,620 INFO    MainThread:12104 [wandb_run.py:_console_start():1584] atexit reg
2021-08-23 17:33:48,623 INFO    MainThread:12104 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.WRAP
2021-08-23 17:33:48,623 INFO    MainThread:12104 [wandb_run.py:_redirect():1495] Wrapping output streams.
2021-08-23 17:33:48,631 INFO    MainThread:12104 [wandb_run.py:_redirect():1519] Redirects installed.
2021-08-23 17:33:48,631 INFO    MainThread:12104 [wandb_init.py:init():565] run started, returning control to user process
2021-08-23 17:33:48,632 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set epochs = 5 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033C5A8B0>>
2021-08-23 17:33:48,633 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb epochs 5 None
2021-08-23 17:33:48,633 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set size = 128 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033C5A8B0>>
2021-08-23 17:33:48,634 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb size 128 None
2021-08-23 17:33:48,635 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set dropout = 0.3 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033C5A8B0>>
2021-08-23 17:33:48,636 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb dropout 0.3 None
2021-08-23 17:33:48,638 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set batch_size = 14 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033C5A8B0>>
2021-08-23 17:33:48,639 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb batch_size 14 None
2021-08-23 17:33:48,640 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set pool_size = [3, 3] - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033C5A8B0>>
2021-08-23 17:33:48,641 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb pool_size [3, 3] None
2021-08-23 17:33:48,642 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set shear_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033C5A8B0>>
2021-08-23 17:33:48,643 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb shear_range 0.4 None
2021-08-23 17:33:48,644 INFO    MainThread:12104 [wandb_config.py:__setitem__():141] config set zoom_range = 0.4 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x000002A033C5A8B0>>
2021-08-23 17:33:48,644 INFO    MainThread:12104 [wandb_run.py:_config_callback():826] config_cb zoom_range 0.4 None
2021-08-23 17:33:48,671 INFO    MainThread:12104 [wandb_init.py:_pause_backend():256] pausing backend
2021-08-23 17:33:48,672 INFO    MainThread:12104 [jupyter.py:save_ipynb():284] not saving jupyter notebook
2021-08-23 17:34:46,628 INFO    MainThread:12104 [wandb_init.py:_resume_backend():265] resuming backend
2021-08-23 17:34:46,693 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting env: {}
2021-08-23 17:34:46,694 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-23 17:34:46,695 INFO    MainThread:12104 [wandb_setup.py:_flush():69] setting login settings: {}
2021-08-23 17:34:46,695 INFO    MainThread:12104 [wandb_init.py:_log_setup():342] Logging user logs to F:\5th sem project\wandb\run-20210823_173446-1yd3waih\logs\debug.log
2021-08-23 17:34:46,696 INFO    MainThread:12104 [wandb_init.py:_log_setup():343] Logging internal logs to F:\5th sem project\wandb\run-20210823_173446-1yd3waih\logs\debug-internal.log
2021-08-23 17:34:46,697 INFO    MainThread:12104 [wandb_init.py:init():375] calling init triggers
2021-08-23 17:34:46,721 INFO    MainThread:12104 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2021-08-23 17:34:46,722 INFO    MainThread:12104 [wandb_init.py:init():395] re-initializing run, found existing run on stack: 1z8qljtr
2021-08-23 17:34:46,723 INFO    MainThread:12104 [wandb_run.py:finish():1254] finishing run khushal/weather-recognization/1z8qljtr
